In [1]:
import os, sys
dir1 = os.path.abspath('..\..')
sys.path.append(dir1+ "\\")

import MetaTrader5 as mt
from datetime import datetime as dt

# custom
from my_jupyter.user import User
from my_jupyter.strategy_manager import StrategyManager
from my_jupyter.operation import Operation
from my_jupyter.strategies.min_max_strategy import MinMaxStrategy
from my_jupyter.market_data_repository import MarketDataRepository
from my_jupyter.filters.moving_average import MovingAverageFilter
from my_jupyter.filters.consequent_limits_counter import ConsequentLimitsCounterFilter
from my_jupyter.filters.directioned_bars_filter import DirectionedBarsFilter

# from Mbox import Mbox
# from boleta_1 import gerar_boleta
# from gerenciamento import Gerenciamento

## GUI's
from daemon_tools import DaemonThreadMini


In [2]:


filters = [DirectionedBarsFilter(candles=5), MovingAverageFilter(), MovingAverageFilter(period=200)]
strategies = [MinMaxStrategy(filters=filters)]
operations = [Operation("WINV23", 1, mt.TIMEFRAME_M1, can_buy=True, can_sell=True)]
user = User(strategies=strategies, operations=operations, trading_time_start=dt(2023,10,5,9,5,0))
market_data_repository = MarketDataRepository()
strategy = StrategyManager(market_data_repository, user)

# PARAMETROS MAIN
kwargs = {
    "strategy": strategy,
}


def main(**kwargs):
    _shift = 0
    strategy: StrategyManager = kwargs["strategy"]
    strategy.run_strategies()
    # print(f"{dt.now().strftime('%d/%m/%Y, %H:%M:%S')} >>> D-{_shift}")
def exec_daemon(**kwargs):
    main(**kwargs)
    # alarme.ring_alarme()

In [3]:
# gerenciamento = Gerenciamento(mt, timeframe, timeframes_dict)

try:
    main(**kwargs)
except Exception as e:
    print(e.with_traceback(__tb=None))
    # Mbox.Alerta("ERRO", "busca de sinais com erro")


In [4]:
# from my_jupyter.daemons.daemon_tools import DaemonThreadMini


# thread_exec = DaemonThreadMini(exec_daemon, seconds=0, mseconds=800, **kwargs)
# thread_exec.start()

In [1]:
import os, sys

dir1 = os.path.abspath("..\..")

if dir1 not in sys.path:
    sys.path.append(dir1 + "\\")
from my_jupyter.indicator.bars_trend_quality_ml import BarsTrendQualityML
from my_jupyter.market_data_repository import MarketDataRepository
from datetime import datetime as dt 
import pandas as pd 
# mt_rep = MarketDataRepository()
# ohlc = mt_rep.read_data("WINV23",mt_rep.mt.TIMEFRAME_M1,6)
# ohlc = mt_rep.mt.copy_rates_from_pos("WINV23", mt_rep.mt.TIMEFRAME_M1, 0, 99999)
# ohlc_0_based = ohlc[::-1]

# from_file  = "dataset\WINV23M1.csv"
# ohlc_df = pd.DataFrame(ohlc)
bars_trend_ml = BarsTrendQualityML()
bars_trend_ml.set_machine_learning_model(from_stock_market_data="WIN$")


In [4]:
from my_jupyter.market_data_repository import MarketDataRepository
from datetime import datetime as dt 
mt_rep = MarketDataRepository()
ohlc = mt_rep.read_data("WINV23",mt_rep.mt.TIMEFRAME_M1,6)
ohlc = mt_rep.mt.copy_rates_from_pos("WINV23", mt_rep.mt.TIMEFRAME_M1, 0, 60)
ohlc_0_based = ohlc[::-1]
# print([ dt.fromtimestamp(i[0]) for i in ohlc_0_based])
# bars_trend_ml.output(ohlc_0_based[1:])
import numpy as np

ohlc_transform = [ohlc_0_based[i:i+6]["close"] for i in range(0, len(ohlc_0_based)-6)]
for i in ohlc_transform:
    print(">>>>>>>", bars_trend_ml.output(i[1:]))


1/1 [==============================] - 0s 76ms/step


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 26ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 37ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 33ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 31ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 26ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 28ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 38ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 24ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 18ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 34ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 33ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 40ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 95ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 40ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 41ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 44ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 51ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 82ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 47ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 73ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 63ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 56ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 72ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 57ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 37ms/step


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 70ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 50ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 35ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 49ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 50ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 49ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 43ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 36ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 55ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 62ms/step


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 65ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 77ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 51ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 60ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 50ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 51ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 52ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 60ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 72ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - ETA: 0s

c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 48ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 47ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 47ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 49ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 31ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 22ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 43ms/step
>>>>>>> [[1. 1. 0.]]
1/1 [==============================] - 0s 25ms/step
>>>>>>> [[1. 1. 0.]]


c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\repo\python\financial-api\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 17ms/step
>>>>>>> [[1. 1. 0.]]
